export const ISOCountries = {
    locale: 'en',
    countries: {
        AF: 'Afghanistan',
        AL: 'Albania',
        DZ: 'Algeria',
        AR: 'Argentina',
        AU: 'Australia',
        AT: 'Austria',
        AZ: 'Azerbaijan',
        BE: 'Belgium',
        BR: 'Brazil',
        BG: 'Bulgaria',
        CA: 'Canada',
        CL: 'Chile',
        CN: 'China',
        CO: 'Colombia',
        HR: 'Croatia',
        CY: 'Cyprus',
        CZ: 'Czech Republic',
        DK: 'Denmark',
        EG: 'Egypt',
        EE: 'Estonia',
        FI: 'Finland',
        FR: 'France',
        GE: 'Georgia',
        DE: 'Germany',
        GR: 'Greece',
        HK: 'Hong Kong',
        HU: 'Hungary',
        IS: 'Iceland',
        IN: 'India',
        ID: 'Indonesia',
        IE: 'Ireland',
        IL: 'Israel',
        IT: 'Italy',
        JP: 'Japan',
        KR: 'South Korea',
        LV: 'Latvia',
        LT: 'Lithuania',
        LU: 'Luxembourg',
        MY: 'Malaysia',
        MX: 'Mexico',
        NL: 'Netherlands',
        NZ: 'New Zealand',
        NO: 'Norway',
        PH: 'Philippines',
        PL: 'Poland',
        PT: 'Portugal',
        RO: 'Romania',
        SA: 'Saudi Arabia',
        RS: 'Serbia',
        SG: 'Singapore',
        SK: 'Slovakia',
        SI: 'Slovenia',
        ZA: 'South Africa',
        ES: 'Spain',
        SE: 'Sweden',
        CH: 'Switzerland',
        TH: 'Thailand',
        TR: 'Turkey',
        UA: 'Ukraine',
        AE: 'United Arab Emirates',
        GB: 'United Kingdom',
        US: 'United States',
        VN: 'Vietnam',
    },
};
